routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['auth'])->group(function () {
	Route::get('/', function () {
	    return view('dashboard');
	})->name('dashboard');

	Route::resource('user', UserController::class);
	Route::get('/user/search', [UserController::class,'search'])->name('search');

});
require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class User extends Model
{
    use HasFactory;
    
    protected $table = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'avatar',
        'department_id',
        'is_leader',
    ];

    public function projects()
    {
        return $this->belongsToMany(Project::class,'user_projects');
    }

    public function department()
    {
        return $this->belongsTo(Department::class);
    }
}

app/Models/Users.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Users extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\View;
use Illuminate\Pagination\Paginator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get all the sharks
        $users = User::paginate(10);
        // load the view and pass the sharks
        return View::make('users.index')
            ->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // load the view and pass the sharks
        return View::make('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        return $this->updateInsert( null, $request );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        // load the view and pass the sharks
        return View::make('users.show')
            ->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // load the view and pass the sharks
        return View::make('users.edit')
            ->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        return $this->updateInsert($user,$request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
    	$user->delete();
        return redirect()->route('user.index');
    }

    public function search()
    {
        return 'as';
    }
    private function updateInsert(User $user = null,UserRequest $request)
    {
        if($user)
            $user->update( $request->all() );
        else
            $user = new User( $request->all() );
        if($request->file('avatar')){
            $path = $request->file('avatar')->store('avatar');
            $user->avatar = $path;
        }
        if($request->has('switch_leader')){
            $user->is_leader = abs(1-$user->is_leader);
        }   
        if( $user->save() ){ 
            if($request->has('projects')){
                $user->projects()->sync($request->input('projects'));
            }
            return redirect( route('user.index') );
        }  else {
            return back()->withInput();
        }
    }
}

app/View/Components/UserForm.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;

class UserForm extends Component
{
    public $user;
    public $action;
    public $method;
    public $disable;
    public $projects;
    public $departments;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(User $user = null,Collection $projects,Collection $departments,$action,$method = 'POST',bool $disable = false)
    {
        $this->user = $user ?: new User();
        $this->projects = $projects;
        $this->departments = $departments;
        $this->action = $action;
        $this->method = $method;
        $this->disable = $disable;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('users.components.user-form');
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Create User')

@section('content')
@php
$action = route('user.store');
@endphp
<x-user-form :projects='$projects' :departments='$departments' :action="$action" >
</x-user-form>
	
@stop

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Create User')

@section('content')
@php
$action = route('user.update',['user' => $user->id]);
$method = 'PUT';
$disable = false;
@endphp
<x-user-form :projects='$projects' :departments='$departments' :user='$user' :action="$action" :method='$method' :disable='$disable'  >
</x-user-form>
	
@stop

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
@php
$heads = [
    'Name',
    'Email',
    'Project',
    'Department',
    ['label' => 'Actions', 'no-export' => true, 'width' => 5],
];
$config = [
    
];
@endphp

<x-adminlte-datatable id="table1" :heads="$heads" :config="$config" head-theme="dark" striped hoverable bordered compressed>
    @foreach($users as $user)
        <tr>
                <td>{!! $user->name !!}</td>
                <td>{!! $user->email !!}</td>
                <td>
                    @foreach($user->projects as $project)
                                {{$project->name}}
                    @endforeach
                </td>
                <td>{!! $user->department->name !!}</td>
                <td>
                    <nobr>    
                    <button class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
                        <a href="{!! route('user.edit',[ 'user'=> $user->id ]) !!}"><i class="fa fa-lg fa-fw fa-pen"></i></a>
                    </button>
                        <form action="{{ route('user.destroy',[ 'user'=> $user->id ]) }}" method="POST" style="display: inline">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                                    <i class="fa fa-lg fa-fw fa-trash"></i>
                            </button>
                        </form>
                    <button class="btn btn-xs btn-default text-teal mx-1 shadow" title="Details">
                        <a href="{!! route('user.show',[ 'user'=> $user->id ]) !!}"><i class="fa fa-lg fa-fw fa-eye"></i></a>
                    </button>
                    </nobr>
                </td>
        </tr>
    @endforeach
</x-adminlte-datatable>



@stop



@section('js')
<script type="text/javascript">
    $('#table1').on( 'keyup', function () {
        table.search( this.value ).draw();
    } );    
</script>
@stop

resources/views/users/show.blade.php
@extends('adminlte::page')

@section('title', 'Create User')

@section('content')
@php
$action = route('user.update',['user' => $user->id]);
$method = 'PUT';
$disable = true;
@endphp
<x-user-form :projects='$projects' :departments='$departments' :user='$user' :action="$action" :method='$method' :disable='$disable'  >
</x-user-form>
	
@stop